name: national_code_validator
description: A Dart library for validating Iranian National Code (کد ملی). This package implements the official validation algorithm for Iranian National Code with proper checks for length, format, and control digit.
version: 1.0.0
repository: https://github.com/smilingmajid/national_code_validator
homepage: https://github.com/smilingmajid/national_code_validator
documentation: https://github.com/smilingmajid/national_code_validator#readme

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
